// <auto-generated />
using System;
using Data.Domain.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200503103114_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c35be0f5-53b5-477c-9bc8-b54c639e6995"),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("eeb2bbef-b79b-4581-8192-4e0e317c062a"),
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("Data.Domain.Entities.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Phone");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4cee576-8f90-4dbf-b1b4-9e9761a5976f"),
                            Count = 100,
                            ManufacturerId = new Guid("eeb2bbef-b79b-4581-8192-4e0e317c062a"),
                            Name = "Pixel 2XL"
                        },
                        new
                        {
                            Id = new Guid("755d18ca-2cb5-435c-82b8-60c2639f59df"),
                            Count = 100,
                            ManufacturerId = new Guid("eeb2bbef-b79b-4581-8192-4e0e317c062a"),
                            Name = "Pixel 4"
                        },
                        new
                        {
                            Id = new Guid("c35be0f5-53b5-477c-9bc8-b54c639e6995"),
                            Count = 100,
                            ManufacturerId = new Guid("eeb2bbef-b79b-4581-8192-4e0e317c062a"),
                            Name = "Iphone 6"
                        });
                });

            modelBuilder.Entity("Data.Domain.Entities.Phone", b =>
                {
                    b.HasOne("Data.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
